name: CI

on:
  push:
    branches: 
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Docker run
      run: docker-compose run project-service bash -c "npm run test --forceExit"

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}