name: CI

on:
  push:
    branches: 
      - dev
      - teste_project_tests
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Run npm install
      run: npm install

    - name: Create env file
      run: |
        touch .env
        echo IP_ADDRESS=${{ secrets.IP_ADDRESS }} >> .env
        echo SECRET=${{ secrets.SECRET }} >> .env
        echo DB_URL_TEST=${{ secrets.DB_URL_TEST }} >> .env
        echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
        cat .env

    - name: Instalar Jest
      run:  npm install -g jest

    - name: Execute tests
      run:  jest --coverage --runInBand --detectOpenHandles --forceExit

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}